FROM apache/airflow:2.10.5-python3.11

RUN python -m pip install --no-cache-dir \
    hdfs==2.7.3 \
    psycopg2-binary==2.9.10 \
    psycopg[binary]==3.2.9 \
    pyarrow==18.1.0 \
    pydantic==2.11.7 \
    PyYAML==6.0.2
